### ISSUE TITLE
truesf not functional beyond chord root (and strange brand-roemer behaviour)

### ISSUE THREAD

**Issue by gwyndaf** [ChordPro/chordpro#261]
Very minor typographic observation: `truesf`doesn't seem to function on sharps or flats beyond a chord's root note. v5.990_006

Example:
```
{title: Accidentals typography}
Works nicely for most chord roots, like [F#] and [Bb]
Even with extensions like [F#maj7] or [Bbm6]
This slash chord [Em/C#] doesn't produce true # symbol in bass
This m7b5: [Bm7b5] doesn't produce true b symbol in b5
```
Resulting output (with only `-X`option and a minimal config setting `truesf=true`: 
[Accidentals_test.cho.pdf](https://github.com/ChordPro/chordpro/files/10273257/Accidentals_test.cho.pdf)

There might be other jazz chord extensions that use ♭ and ♯, but the example above is about as far as I go in that direction :)

Secondary (but possibly more significant) issue: testing the same sample with the built-in `brandroemer` config (and `-X`) seems to produce strange results, losing some ♯ ♭ symbols altogether:
[Accidentals_test-BR.cho.pdf](https://github.com/ChordPro/chordpro/files/10273234/Accidentals_test-BR.cho.pdf)

The Bbm6 retains the 'b' even if it's not ♭. It's reported as 'unknown chord' so possibly bypasses the `display`settings in the config file. Which leads me to suspect it might be because the `brandroemer` config includes actual Unicode ♭ and ♯ symbols for chords that are defined there.

I'm guessing it might work ok with fonts that support ♭ and ♯ characters, but could confuse the unprepared, including those using the built-in default fonts.

**Comment by sciurius** [comment]
Sometimes Perl has its magic even for me... Fixed in 5.990_007.

**Comment by gwyndaf** [comment]
Fantastic: that seems to solve the primary issue.

Doesn't seem to resolve the secondary brandroemer issue (with default fonts), but the automatic replacement of `#`/`b` with `♯`/`♭` now works nicely, so I guess the config can simply use basic `#` and `b`. Tested with the attached sample, and seems to work better. (Not something I use myself, but gives a useful insight into using Pango markup in `display`).
[brandtroemer.json.txt](https://github.com/ChordPro/chordpro/files/10278503/brandtroemer.json.txt)

Side note: with the `-X`option, output defaults to italic chord names, while the `ChordProSymbols.ttf` font (fallback for automatic `truesf` replacement, I believe) is purely Roman type, so looks a bit different. I've already hacked that font file a little to make `♯`/`♭` bold to match my own chord name style, so maybe it's worth adding bold/italic/bolditalic variants.

I'm guessing it could involve more work than creating additional font files, and might need internal program support to use the font weight and slant that matches the chord/note names.

**Comment by gwyndaf** [comment]
I've tried using `chordpro -X --config guitar-br --define settings.truesf=1 ` and the same results as previously.
[Accidentals_test.cho.pdf](https://github.com/ChordPro/chordpro/files/10279735/Accidentals_test.cho.pdf)

The difference seems to be I have `-X` to use all default settings, except what's on the command line.

Interestingly, I get a space after F and B instead of sharp and flat symbols. Not even the crossed-through box that's common if a font doesn't contain the right character.

I'll investigate further: it could be a font issue on my system (Linux Debian), or maybe because I've modified the ChordProSymbols font.

**Comment by sciurius** [comment]
Ah, I missed the initial F# and Bb. This produces correct results:

    chordpro -X --def settings.truesf=1 sf.cho -C Helvetica

(I added Helvetica as chord font to correct for the uglyness of italic chords and straight symbols.)

In the case of BrandtRoemer, `F#` is displayed as `F♯`. With truesf, `#` and `♭` are replaced by glyphs from the fallback ChordProSymbols font. But since `F#` is displayed as `F♯` there is no `#` to replace...

Can you try 5.990_009?

**Comment by gwyndaf** [comment]
Sorry, the first two lines in my example reflected only my initial issue, not the secondary one, so it wasn't clearly signposted!

5.990_009 seems to have fixed it.
